[workspace]
members = [
  "app",
  "hotkeys",
]

[patch.crates-io]
# eframe = {path = "../egui/eframe"}
# eframe = {git = "https://github.com/AlexxxRu/egui.git", branch = "feature/forward_window"}

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
